bingos = {
    'kubulek_v3': [
        'Francuski Utwór',
        'FRAZA: "Ale króciutko!"',
        'Płynna zmiana tematu',
        'Problemy z połączeniem',
        'Utwór z dedykacją',
        'Pierogi i inne pyszności',
        'Zmiana koloru oświetlenia w studiu',
        'Piosenka dnia z czapy',
        'Kuba szkaluje Marcela',
        'FRAZA: "Królu złoty!"',
        'Kuba wychodzi na papierosa',
        'Ktoś wspomina Trójkę',
        'img', // NIE ZMIENIAĆ!
        'Rozmowa z puszki',
        'Wczorajszy pan Marek',
        'Pan Adam z Mazur',
        'Kontrower-syjny temat reportażu',
        'Czarny humor Kuby',
        'FRAZA: "Może następnym razem!"',
        'Struclowa Wielka Płyta',
        'Przerwany monolog słuchacza',
        'Utwór Beach Boys',
        'Żona Kuby lub Lucek',
        'Kuczyński szkaluje RPP',
        'Kuba potakuje rozmówcy',
        ],
    'kubulek_v4': [
        'Kontrower-syjny temat reportażu',
        'Zmiana kolorów w studiu',
        'Płynna zmiana tematu',
        'Kuba szkaluje Marcela',
        'TEMAT: Nietypowe święto',
        'Pierogi i inne pyszności',
        'Utwór z dedykacją',
        'FRAZA: "Królu Złoty!"',
        'Struclowa Wielka Płyta',
        'Piosenka dnia z czapy',
        'Utwór Beach Boys',
        'Nawiązanie do żeglarstwa',
        'img', // NIE ZMIENIAĆ!
        'FRAZA: "Może następnym razem"',
        'Wczorajszy pan Marek',
        'Czarny humor Kuby',
        'Kuba wspomina o Lucku',
        'Segment grany z puszki',
        'Pan Adam z Mazur',
        'Ktoś wspomina Trójkę',
        'Utwór francusko-języczny',
        'Przerwany monolog słuchacza',
        'Usterka na linii z rozmówcą',
        'Opóźniony serwis',
        'Sołtys pogania Kubę',
        ],
    'kubulek_v5': [
        'Usterka na linii z rozmówcą',
        'FRAZA: "Nie brak opinii"',
        'Pierogi i inne pyszności',
        'Utwór Beach Boys',
        'Wczorajszy pan Marek',
        'Reklama podcastów albo Boxu',
        'Francusko-języczny utwór',
        'TEMAT: Nietypowe święto',
        'Czarny humor Kuby',
        'Segment grany z puszki',
        "Utwór Andy'ego Williamsa",
        'Nawiązanie do Żeglarstwa',
        'img', // NIE ZMIENIAĆ!
        'FRAZA: "Królu złoty"',
        'Rozmówca jest patronem',
        'Kuba szkaluje Marcela',
        'Struclowa Wielka Płyta',
        'Przerwany monolog słuchacza',
        'Pan Adam z Mazur',
        'Oksfordzki akcent Kuby',
        'Piosenka dnia z czapy',
        'Ktoś wspomina Trójkę',
        'Kuczyński szkaluje prezesa NBP',
        'Opóźniony serwis',
        'Kontrower-syjny reportaż',
        ],
    'santa': [
        'Reklama bombek lub boxu',
        'Strucel z dzwoneczkami',
        'Bitwa poza finałem',
        'Nawiązanie do Żeglarstwa',
        'Pan Adnan na antenie',
        'Pan Adam z Mazur',
        'Segment grany z puszki',
        'Fant sprzedany za <1 Jandę',
        'Słuchacz proponuje fanty',
        'Opóźniony serwis',
        'FRAZA: "Królu złoty"',
        'Szkalowanie Marcela',
        'Oferta na fant pada po finale',
        'Last Christmas z przyczajki',
        'Ktoś kroi cebulę na antenie',
        'Kuba pośpiesza Sołtysa',
        'FRAZA: "Ąąąąą"',
        'FRAZA: "Ukłony!"',
        'Brak kontaktu z finalistą',
        'Ktoś wspomina Trójkę',
        'Licytacja opóźnia listę',
        'Kuba wychodzi na papierosa',
        'Dzielona wygrana',
        'Licytujący już kiedyś wygrał licytację',
        'Piosenka o Pewnej Rybie',
        'Dźwięki zachwytu w tle',
        'Prośba o płytę od Niedźwiedzia',
        'Kawa na pocieszenie',
        'Oferta za x333 zł',
        'Słuchacz wyłudza kubek',
        'Oferta zaraz przed serwisem',
        'Problemy z połączeniem',
        'Dziecko przy telefonie',
        'Słuchacze rozwiązują problem przed końcem audycji',
        ],
    'zozun': [
        'Marcel szkalowany',
        'Złote myśli Ernesta',
        'Segment z puszki',
        'Słuchacz szkalowany',
        'Wyciszenie słuchacza',
        'Przekręcone imię słuchacza',
        'Wywołanie gównoburzy',
        'Wspomnienie Trójki',
        'Przekręcone nazwisko gościa',
        'Rozmowa o alkoholu',
        'He He He',
        'Słaba jakość u rozmówcy',
        'img',
        'Reportaż budzący silne emocje',
        'Szkalowanie RPP',
        'Słuchacz jest patronem',
        'Kontrower-syjne stanowisko',
        'Słuchacz pyta o Kubę',
        'Sympatyczny Pan Rafał',
        'Pan Adam z Mazur',
        'Sport o czasie',
        'Wspomnienie starego filmu lub serialu',
        'Ernest myśli że jest świętszy od papieża',
        'Przekręcony tytuł piosenki',
        'Kubulkowe sztrucle',
    ],
    'misiek': [
        'Utwór Reggae w 1. godzinie',
        'Utwór Reggae w 2. godzinie',
        'Utwór Reggae w 3. godzinie',
        'Działalność społeczna',
        'Rozmówca okazuje się zaproszony przez Miśka',
        'Historia poznania danej osoby',
        'TEMAT: Sport',
        'Aluzja do zielonego',
        'Misiek tłumaczy słuchaczowi rzeczywistość',
        'Popisy językiem polskim',
        'Wspomnienie rocznicy',
        'Szkalowanie RPP',
        'Słuchacz pyta o Kubę',
        'TEMAT: Psy',
        'Wspomnienie Trójki',
        'Piosenka francuska',
        'Bob Marley',
        'Wspomnienie miejscowości pochodzenia',
        'Pan Adam z Mazur',
        'Opóźniony serwis',
        'Rozmówca jest wczorajszy',
        'Słaba jakość u rozmówcy',
        'Reportaż budzący silne emocje',
        'Przerwany monolog słuchacza',
        'TEMAT: Nietypowe święto',
        'Struclowa wielka płyta',
        'Segment grany z puszki',
        'Szkalowanie polskich piłkarzy',
        'Misiek oburzony'
    ],
    'kubulekrandom': [
        'Czarny humor Kuby',
        'Francusko-języczny utwór',
        'FRAZA: "A jakże!"',
        'FRAZA: "A wie pan że..."',
        'FRAZA: "Ale króciutko!"',
        'FRAZA: "Królu złoty!"',
        'FRAZA: "Może następnym razem"',
        'FRAZA: "Nie brak opinii"',
        'FRAZA: "Panie kolego"',
        'FRAZA: "Do tego stopnia"',
        'FRAZA: "Ukłony!"',
        'FRAZA: "Bliżej mikrofonu"',
        'FRAZA: "Bliżej tubki"',
        'Kuba dedykuje utwór',
        'Pan Marek skarży się na zabieranie czasu wypowiedzi',
        'Szlagier z PRLu',
        'Przedwojenny szlagier',
        'Kuba mówi o żonie lub o Lucku',
        'Kuba podaje złą godzinę',
        'Kuba potakuje rozmówcy',
        'Marek wspomina swoją córkę',
        'Kuba wychodzi na papierosa',
        'Kuczyński szkaluje RPP',
        'Nawiązanie do żeglarstwa',
        'Oksfordzki akcent Kuby',
        'Opóźniony serwis',
        'Pan Adam z Mazur',
        'Pierogi i inne pyszności',
        'Piosenka dnia z czapy',
        'Płynna zmiana tematu',
        'Pominięta prognoza pogody',
        'Przerwany monolog słuchacza',
        'Reklama podcastów albo Boxu',
        'Reportaż budzący silne emocje',
        'Rozmówca jest patronem',
        'Segment grany z puszki',
        'Słaba jakość u rozmówcy',
        'Sołtys pogania Kubę',
        'Struclowa Wielka Płyta',
        'Szkalowanie Marcela',
        'TEMAT: Nietypowe święto',
        'Kuba udaje, że zna lub czekał na rozmówcę',
        'Usterka na linii z rozmówcą',
        "Utwór Andy'ego Williamsa",
        'Utwór Beach Boys',
        'Utwór Franka Sinatry',
        'Utwór Queen',
        'Rozmówca jest wczorajszy',
        'Wspomnienie Trójki',
        'FRAZA: "Ąąąąą"',
    ],
    'tiptop': [
        'Fraza "domówka orlikówka"',
        'Utwór z sieciówkowej przymierzalni',
        'Narzekający Michał',
        'Fotografia wysłana przez słuchacza',
        'Słuchacz chwalący Tip Top',
        'Żółć o 21:37',
        'Nawiązanie do PIS w serwisie informacyjnym',
        'Nowość od discorda',
        'Fraza "tylko jedna nowość"',
        'Fraza "Państwo tak zdecydowali"',
        'Suchy żart Michała',
        'Zaproszenie do patronowania',
        'Utwór discorda spadający z listy',
        'Nawiązanie do The Patrons',
        'Długi monolog Michała',
        'Adrianna prowadzi serwis',
        'Michał zagaduje serwisanta po serwisie',
        'Fraza "liczna państwa obecność"',
        'Określenie "pieśń"',
        'Matylda na podium',
        'Nawiązanie do jedzenia',
        'Słuchacz domaga się konkretnego utworu ',
        'Utwór francusko-języczny',
        'Komunikat "piosenka dla dorosłych"',
    ]
}
