bingos = {
    'kubulek_v3': [
        'Francuski Utwór',
        'FRAZA: "Ale króciutko!"',
        'Płynna zmiana tematu',
        'Problemy z połączeniem',
        'Utwór z dedykacją',
        'Pierogi i inne pyszności',
        'Zmiana koloru oświetlenia w studiu',
        'Piosenka dnia z czapy',
        'Kuba szkaluje Marcela',
        'FRAZA: "Królu złoty!"',
        'Kuba wychodzi na papierosa',
        'Ktoś wspomina Trójkę',
        'img', // NIE ZMIENIAĆ!
        'Rozmowa z puszki',
        'Wczorajszy pan Marek',
        'Pan Adam z Mazur',
        'Kontrower-syjny temat reportażu',
        'Czarny humor Kuby',
        'FRAZA: "Może następnym razem!"',
        'Struclowa Wielka Płyta',
        'Przerwany monolog słuchacza',
        'Utwór Beach Boys',
        'Żona Kuby lub Lucek',
        'Kuczyński szkaluje RPP',
        'Kuba potakuje rozmówcy',
        ],
    'kubulek_v4': [
        'Kontrower-syjny temat reportażu',
        'Zmiana kolorów w studiu',
        'Płynna zmiana tematu',
        'Kuba szkaluje Marcela',
        'TEMAT: Nietypowe święto',
        'Pierogi i inne pyszności',
        'Utwór z dedykacją',
        'FRAZA: "Królu Złoty!"',
        'Struclowa Wielka Płyta',
        'Piosenka dnia z czapy',
        'Utwór Beach Boys',
        'Nawiązanie do żeglarstwa',
        'img', // NIE ZMIENIAĆ!
        'FRAZA: "Może następnym razem"',
        'Wczorajszy pan Marek',
        'Czarny humor Kuby',
        'Kuba wspomina o Lucku',
        'Segment grany z puszki',
        'Pan Adam z Mazur',
        'Ktoś wspomina Trójkę',
        'Utwór francusko-języczny',
        'Przerwany monolog słuchacza',
        'Usterka na linii z rozmówcą',
        'Opóźniony serwis',
        'Sołtys pogania Kubę',
        ],
    'kubulek_v5': [
        'Usterka na linii z rozmówcą',
        'FRAZA: "Nie brak opinii"',
        'Pierogi i inne pyszności',
        'Utwór Beach Boys',
        'Wczorajszy pan Marek',
        'Reklama podcastów albo Boxu',
        'Francusko-języczny utwór',
        'TEMAT: Nietypowe święto',
        'Czarny humor Kuby',
        'Segment grany z puszki',
        "Utwór Andy'ego Williamsa",
        'Nawiązanie do Żeglarstwa',
        'img', // NIE ZMIENIAĆ!
        'FRAZA: "Królu złoty"',
        'Rozmówca jest patronem',
        'Kuba szkaluje Marcela',
        'Struclowa Wielka Płyta',
        'Przerwany monolog słuchacza',
        'Pan Adam z Mazur',
        'Oksfordzki akcent Kuby',
        'Piosenka dnia z czapy',
        'Ktoś wspomina Trójkę',
        'Kuczyński szkaluje prezesa NBP',
        'Opóźniony serwis',
        'Kontrower-syjny reportaż',
        ],
    'santa': [
        'Reklama bombek lub boxu',
        'Strucel z dzwoneczkami',
        'Bitwa poza finałem',
        'Pan Adnan na antenie',
        'Fant sprzedany za <1 Jandę',
        'Słuchacz proponuje fanty',
        'Opóźniony serwis',
        'Oferta na fant pada po finale',
        'Last Christmas z przyczajki',
        'Ktoś kroi cebulę na antenie',
        'Kuba pośpiesza Sołtysa',
        'Brak kontaktu z finalistą',
        'img', // NIE ZMIENIAĆ!
        'Ktoś wspomina Trójkę',
        'Licytacja opóźnia listę',
        'Dzielona wygrana',
        'Piosenka o Pewnej Rybie',
        'Dźwięki zachwytu w tle',
        'Prośba o płytę od Niedźwiedzia',
        'Kawa na pocieszenie',
        'Oferta za x333 zł',
        'Słuchacz wyłudza kubek',
        'Oferta zaraz przed serwisem',
        'Kuba szkaluje Marcela',
        'Problemy z połączeniem',
        ],
    'zozun': [
        'Rosyjski Utwór',
        'Wspomnienie Trójki',
        'Ernest broni szczepień',
        'Słaba jakość u rozmówcy',
        'Wywołanie gównoburzy',
        'He He He',
        'Zmiana oświetlenia w studiu',
        'Słuchacz szkalowany',
        'Marcel szkalowany',
        'Wyciszenie słuchacza',
        'Przekręcone nazwisko gościa',
        'Przekręcone nazwisko słuchacza',
        'img',
        'Przekręcony tytuł piosenki',
        'Słuchacz pyta o Kubę',
        'Wspomnienie starego filmu lub serialu',
        'Kontrower-syjne stanowisko',
        'Pierogi i inne pysznośći',
        'Sytuacja na granicy',
        'Wczorajszy Pan Marek',
        'Pan Adam z Mazur',
        'Kubulkowe sztrucle',
        'Utwory z podróży i wakacji',
        'Szkalowanie RPP',
        'Sympatyczny Pan Rafał',
    ]
}